// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: user.sql

package db

import (
	"context"
	"time"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    username, email, password, subscription, token, refresh_token, user_cart, role
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, username, email, password, subscription, token, refresh_token, user_cart, role, created_at, updated_at
`

type CreateUserParams struct {
	Username     string  `json:"username"`
	Email        string  `json:"email"`
	Password     string  `json:"password"`
	Subscription bool    `json:"subscription"`
	Token        string  `json:"token"`
	RefreshToken string  `json:"refresh_token"`
	UserCart     []int32 `json:"user_cart"`
	Role         string  `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.Password,
		arg.Subscription,
		arg.Token,
		arg.RefreshToken,
		arg.UserCart,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.Subscription,
		&i.Token,
		&i.RefreshToken,
		&i.UserCart,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getSubscribedUsers = `-- name: GetSubscribedUsers :many
SELECT id, username, email, password, subscription, token, refresh_token, user_cart, role, created_at, updated_at FROM users
WHERE
    subscription = true
ORDER BY username
`

func (q *Queries) GetSubscribedUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, getSubscribedUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.Password,
			&i.Subscription,
			&i.Token,
			&i.RefreshToken,
			&i.UserCart,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUser = `-- name: GetUser :one
SELECT id, username, email, password, subscription, token, refresh_token, user_cart, role, created_at, updated_at FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.Subscription,
		&i.Token,
		&i.RefreshToken,
		&i.UserCart,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserForUpdate = `-- name: GetUserForUpdate :one
SELECT id, username, email, password, subscription, token, refresh_token, user_cart, role, created_at, updated_at FROM users
WHERE id = $1 LIMIT 1
FOR NO KEY UPDATE
`

func (q *Queries) GetUserForUpdate(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserForUpdate, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.Subscription,
		&i.Token,
		&i.RefreshToken,
		&i.UserCart,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, email, password, subscription, token, refresh_token, user_cart, role, created_at, updated_at FROM users
ORDER BY username
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.Password,
			&i.Subscription,
			&i.Token,
			&i.RefreshToken,
			&i.UserCart,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
    set username = $1,
    email = $2,
    password = $3,
    subscription = $4,
    token = $5,
    refresh_token = $6,
    user_cart = $7,
    updated_at = $8
WHERE id = $9
RETURNING id, username, email, password, subscription, token, refresh_token, user_cart, role, created_at, updated_at
`

type UpdateUserParams struct {
	Username     string    `json:"username"`
	Email        string    `json:"email"`
	Password     string    `json:"password"`
	Subscription bool      `json:"subscription"`
	Token        string    `json:"token"`
	RefreshToken string    `json:"refresh_token"`
	UserCart     []int32   `json:"user_cart"`
	UpdatedAt    time.Time `json:"updated_at"`
	ID           int64     `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.Username,
		arg.Email,
		arg.Password,
		arg.Subscription,
		arg.Token,
		arg.RefreshToken,
		arg.UserCart,
		arg.UpdatedAt,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.Subscription,
		&i.Token,
		&i.RefreshToken,
		&i.UserCart,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
